title: Darren Steptoe
description: "Strategy • Systems • Story"

url: ""
baseurl: ""

collections:
  papers:
    output: true
    permalink: /research/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: site
      description: "Strategy • Systems • Story"

  - scope:
      path: ""
      type: papers
    values:
      layout: paper

  - scope:
      path: ""
      type: posts
    values:
      layout: post

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed

author: Darren Steptoe

exclude:
  - vendor
  - vendor/bundle
  - .bundle
  - node_modules
  - tools
  - docs
  - package.json
  - package-lock.json
  - yarn.lock
  - pnpm-lock.yaml
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - .ruby-version
